services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: simple-django-app:latest
    command: uv run gunicorn api.wsgi:application --bind 0.0.0.0:8000 --workers 4
    container_name: backend
    environment:
      - DEBUG=${DEBUG:-1}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://frontend, http://localhost:8080}
    volumes:
      - static:/app/staticfiles
      - backend_db:/app/db
    restart: unless-stopped

    networks:
      - caddy_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    image: simple-frontend-app:latest
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - caddy_network

volumes:
  static:
  backend_db:

networks:
  caddy_network:
